USE [master]
GO

/****** Object:  Database [redditscrapeDB]    Script Date: 12/17/2020 8:06:23 PM ******/
CREATE DATABASE [redditscrapeDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'redditscrapeDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\redditscrapeDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'redditscrapeDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\redditscrapeDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [redditscrapeDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [redditscrapeDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [redditscrapeDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [redditscrapeDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [redditscrapeDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [redditscrapeDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [redditscrapeDB] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [redditscrapeDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [redditscrapeDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [redditscrapeDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [redditscrapeDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [redditscrapeDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [redditscrapeDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [redditscrapeDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [redditscrapeDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [redditscrapeDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [redditscrapeDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [redditscrapeDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [redditscrapeDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [redditscrapeDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [redditscrapeDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [redditscrapeDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [redditscrapeDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [redditscrapeDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [redditscrapeDB] SET  MULTI_USER 
GO

ALTER DATABASE [redditscrapeDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [redditscrapeDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [redditscrapeDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [redditscrapeDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [redditscrapeDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [redditscrapeDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [redditscrapeDB] SET  READ_WRITE 
GO

